name: Windows build WIP

# Run only on tags
on:
  push:
#    tags:
#      - '**'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.*

      - name: Install NSIS
        uses: repolevedavaj/install-nsis@v1.0.1
        with:
          nsis-version: '3.10'

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_C_COMPILER=cl
          -S ${{ github.workspace }}
          -B ${{ steps.strings.outputs.build-output-dir }}

      - name: Build and package
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release --target package

      - name: Upload cpack failure log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cpack_failure_log
          path: ${{ steps.strings.outputs.build-output-dir }}/_CPack_Packages/win64/NSIS/*.log
          retention-days: 5

      - name: Show build output
        if: always()
        run: dir ${{ steps.strings.outputs.build-output-dir }}

      - name: Show release dir
        if: always()
        run: dir ${{ steps.strings.outputs.build-output-dir }}/Release/

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: windows_installer
          path: ${{ steps.strings.outputs.build-output-dir }}/Aqua-mixtura_*.exe
          retention-days: 5
